version: '3'
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:3.6
    networks:
      - gateway
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=chatdb
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  chat-server:
    container_name: chat-server
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-server:latest
    networks:
      - gateway
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo

networks:
   gateway:
     driver: "bridge"
